#!/usr/bin/env bash
# Compatibility wrapper: all units are generated by the shared installer.
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
HB_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
exec sudo env HB_ROOT="$HB_ROOT" bash "$HB_ROOT/r1_integration/scripts/install_services.sh"
