# Autogenerated by launch_sim.sh
ROBOT = "g1"
DOMAIN_ID = 1
INTERFACE = "lo"
ROBOT_SCENE = "../unitree_robots/" + ROBOT + "/scene.xml"
USE_JOYSTICK = False
PRINT_SCENE_INFORMATION = True
ENABLE_ELASTIC_BAND = False
SIMULATE_DT = 0.005
VIEWER_DT = 0.02
